# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-30T11:48:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Pets(BaseModel):
    __root__: List[Pet]


class Error(BaseModel):
    code: int
    message: str
