# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-08-06T15:04:52+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class BadRequestError(BaseModel):
    message: str


class UnprocessableEntityError(BaseModel):
    message: str


class InternalServerError(BaseModel):
    message: str


class NotFoundError(BaseModel):
    message: str


class Pets(BaseModel):
    pets: List[Pet]
