/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package call_numpy;

import java.io.File;
import org.graalvm.polyglot.*;


public class App {
    public static void main(String[] args) {
        Context context = Context.newBuilder().allowAllAccess(true).build();
        try {
            File program = new File(ClassLoader.getSystemClassLoader().getResource("./calculate.py").toURI());
            context.eval(Source.newBuilder("python", program).build());

            int[] a = {1, 2};
            int[] b = {2, 3};

            Value calculateFunction = context.getBindings("python").getMember("calculate");
            Value result = calculateFunction.execute(a, b);
            System.out.println(result.getArrayElement(0));
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
        }
        System.out.println("DONE");
    }
}
