# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-08-13T08:36:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Pets(BaseModel):
    pets: List[Pet]


class Error(BaseModel):
    code: int
    message: str
