# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-30T12:41:25+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI, Path

from .schema import HTTPValidationError, Pets

app = FastAPI(
    version='1.0.0',
    title='Swagger Petstore',
    license={'name': 'MIT'},
    servers=[{'url': 'http://localhost:8000', 'description': 'local'}],
)


@app.get(
    '/pets',
    response_model=Pets,
    responses={
        '422': {'model': HTTPValidationError},
        '500': {'model': HTTPValidationError},
    },
    tags=['pets'],
)
def list_pets(limit: Optional[int] = None) -> Union[Pets, HTTPValidationError]:
    """
    List all pets
    """
    pass


@app.post(
    '/pets',
    response_model=None,
    responses={
        '422': {'model': HTTPValidationError},
        '500': {'model': HTTPValidationError},
    },
    tags=['pets'],
)
def create_pets() -> Union[None, HTTPValidationError]:
    """
    Create a pet
    """
    pass


@app.get(
    '/pets/{pet_id}',
    response_model=Pets,
    responses={
        '422': {'model': HTTPValidationError},
        '500': {'model': HTTPValidationError},
    },
    tags=['pets'],
)
def show_pet_by_id(
    pet_id: str = Path(..., alias='petId')
) -> Union[Pets, HTTPValidationError]:
    """
    Info for a specific pet
    """
    pass
