# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-30T12:41:25+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Message(BaseModel):
    content: str
    values: List[int]


class Reply(BaseModel):
    content: str


class MessageError(BaseModel):
    msg: str
    type: str

class CustomHTTPValidationError(BaseModel):
    msg: str
