components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    RequestBody:
      properties:
        keyword:
          title: Keyword
          type: string
      required:
      - keyword
      title: RequestBody
      type: object
    ResponseBody:
      properties:
        items:
          items:
            type: string
          title: Items
          type: array
      required:
      - items
      title: ResponseBody
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /ping:
    get:
      operationId: ping_ping_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Ping
  /sample:
    post:
      operationId: sample_sample_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseBody'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Sample
